"""remove parent_id from notes

Revision ID: 4bb85a18d388
Revises: 7a4df2813996
Create Date: 2026-06-10 18:16:54.279590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb85a18d388'
down_revision: Union[str, Sequence[str], None] = '7a4df2813996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('notebooks', sa.Column('type', sa.String(), nullable=True))
    op.execute("UPDATE notebooks SET type = 'notebook' WHERE type IS NULL")
    op.alter_column('notebooks', 'type', nullable=False)
    
    op.drop_constraint('notes_parent_id_fkey', 'notes', type_='foreignkey')  # ← nombre correcto
    op.drop_column('notes', 'parent_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('notes_parent_id_fkey'), 'notes', 'notes', ['parent_id'], ['id'])
    op.drop_column('notebooks', 'type')
    # ### end Alembic commands ###
