"""add parent_id to notes

Revision ID: 7a4df2813996
Revises: cce385fdb41a
Create Date: 2026-06-10 17:06:09.270118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4df2813996'
down_revision: Union[str, Sequence[str], None] = 'cce385fdb41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'notes', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'parent_id')
    # ### end Alembic commands ###
