"""restructure notebooks and add relationship to notes

Revision ID: b0119664488b
Revises: fa149e5b83b1
Create Date: 2026-05-23 17:48:14.232349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0119664488b'
down_revision: Union[str, Sequence[str], None] = 'fa149e5b83b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notes', 'notebooks', ['notebook_id'], ['id'])
    op.drop_column('notes', 'child_note_id')
    op.drop_column('notes', 'date')
    op.drop_column('notes', 'parent_folder_id')
    op.drop_column('notes', 'owner_id')
    op.drop_column('notes', 'bibliography_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('bibliography_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('parent_folder_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('child_note_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    # ### end Alembic commands ###
