"""add bibliographies and notes bibliographies

Revision ID: cce385fdb41a
Revises: 4932ae0e0e5c
Create Date: 2026-06-04 12:54:51.567256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce385fdb41a'
down_revision: Union[str, Sequence[str], None] = '4932ae0e0e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # notes_notebooks ya existe, no recrear
    op.create_table('notes_bibliographies',
        sa.Column('note_id', sa.Integer(), nullable=False),
        sa.Column('bibliography_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['note_id'], ['notes.id']),
        sa.ForeignKeyConstraint(['bibliography_id'], ['bibliographies.id']),
        sa.PrimaryKeyConstraint('note_id', 'bibliography_id')
    )
    op.add_column('bibliographies', sa.Column('description', sa.String(), nullable=True))
    op.add_column('bibliographies', sa.Column('type', sa.String(), nullable=True))
    op.add_column('bibliographies', sa.Column('url', sa.String(), nullable=True))
    op.drop_column('bibliographies', 'notebook_id')
    op.drop_column('bibliographies', 'date')
    op.drop_column('bibliographies', 'child_note_id')
    op.drop_column('bibliographies', 'owner_id')
    op.drop_column('bibliographies', 'content')
    op.drop_column('bibliographies', 'parent_folder_id')
    op.drop_column('bibliographies', 'bibliography_id')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bibliographies', sa.Column('bibliography_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bibliographies', sa.Column('parent_folder_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bibliographies', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('bibliographies', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bibliographies', sa.Column('child_note_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bibliographies', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('bibliographies', sa.Column('notebook_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bibliographies', 'url')
    op.drop_column('bibliographies', 'type')
    op.drop_column('bibliographies', 'description')
    op.create_table('notes_notebooks',
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notebook_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('notes_notebooks_note_id_fkey')),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], name=op.f('notes_notebooks_notebook_id_fkey')),
    sa.PrimaryKeyConstraint('note_id', 'notebook_id', name=op.f('notes_notebooks_pkey'))
    )
    # ### end Alembic commands ###
