"""add description to notebooks

Revision ID: dfce6f72a1f0
Revises: b0119664488b
Create Date: 2026-05-28 16:39:08.764769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfce6f72a1f0'
down_revision: Union[str, Sequence[str], None] = 'b0119664488b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('description', sa.String(), nullable=True))
    op.add_column('notebooks', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notebooks', 'notebooks', ['parent_id'], ['id'])
    op.drop_column('notebooks', 'child_note_id')
    op.drop_column('notebooks', 'parent_folder_id')
    op.drop_column('notebooks', 'content')
    op.drop_column('notebooks', 'date')
    op.drop_column('notebooks', 'notebook_id')
    op.drop_column('notebooks', 'owner_id')
    op.drop_column('notebooks', 'bibliography_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('bibliography_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('notebooks', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('notebooks', sa.Column('notebook_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('notebooks', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notebooks', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notebooks', sa.Column('parent_folder_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('notebooks', sa.Column('child_note_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notebooks', type_='foreignkey')
    op.drop_column('notebooks', 'parent_id')
    op.drop_column('notebooks', 'description')
    # ### end Alembic commands ###
